### ISSUE TITLE
The 'Pods-Runner' target has transitive dependencies that include static binaries

### ISSUE THREAD

**Issue by coffee4u** [lishuhao/sy_flutter_wechat#1]
你好，
不知道邮件你会不会看，我在yaml文件里添加这个插件并且get之后，在xcode里面去执行pod install,会产生以下问题：
因为加了你的pod之后，会去拉wechatopensdk,但是里面好像会含有.a文件，导致编pod的时候失败了，目前卡在这里，不知道有没有什么解决办法？
Installing WechatOpenSDK (1.8.3)

Using firebase_auth (0.0.1)

Using firebase_core (0.0.1)

Using flutter_facebook_login (0.0.1)

Using google_sign_in (0.0.1)

Using nanopb (0.3.901)

Installing sy_flutter_wechat (0.0.1)

[!] The 'Pods-Runner' target has transitive dependencies that include static binaries: (/Users/chenbin/geproject/Client/GEP_Flutter/gep/ios/Pods/WechatOpenSDK/WeChatSDK1.8.3/libWeChatSDK.a)

**Comment by lishuhao** [comment]
@coffee4u please update sy_flutter_wechat to 0.2.1
If you still have questions, welcome feedback
