### ISSUE TITLE
调用支付有问题

### ISSUE THREAD

**Issue by haibin2017** [lishuhao/sy_flutter_wechat#5]
这样调用的
`SyFlutterWechat.pay(SyPayInfo.fromJson(json.decode(payStr))).then((
            result) {
print("支付结果");
print(result);
});`
提示这个
`MissingPluginException(No implementation found for method pay on channel sy_flutter_wechat)
I/flutter (20820): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:300:7)`
安卓手机测试的
register的时候就有问题
![image](https://user-images.githubusercontent.com/30611593/57364578-1150b800-71b6-11e9-986f-ffc11bc6426c.png)

**Comment by haibin2017** [comment]
![image](https://user-images.githubusercontent.com/30611593/57364241-5e805a00-71b5-11e9-9b56-37044e9e3638.png)

**Comment by haibin2017** [comment]
android手机测试

**Comment by haibin2017** [comment]
没有问题了，重启下就好了。。

**Comment by haibin2017** [comment]
但还是调不起支付界面来

**Comment by haibin2017** [comment]
是apk 签名问题

**Comment by liuchunboVampire** [comment]
> 是apk 签名问题

payResult返回 fail，register返回了true，而且签名检查了也没问题，请问还能有什么情况会导致这个fail呢？分享没问题，就支付一直不行
