### ISSUE TITLE
微信支付回调 errcode -1

### ISSUE THREAD

**Issue by swellee** [lishuhao/sy_flutter_wechat#6]
连接红米手机调试，打印信息显示sign验证通过，之后的打印信息如下：
D/MicroMsg.SDK.MMessageAct(16069): send, targetPkgName = com.tencent.mm, targetClassName = com.tencent.mm.plugin.base.stub.WXPayEntryActivity
I/Timeline(16069): Timeline: Activity_launch_request time:409970045 intent:Intent { flg=0x18000000 cmp=com.tencent.mm/.plugin.base.stub.WXPayEntryActivity (has extras) }
D/MicroMsg.SDK.MMessageAct(16069): send mm message, intent=Intent { flg=0x18000000 cmp=com.tencent.mm/.plugin.base.stub.WXPayEntryActivity (has extras) }
I/MicroMsg.SDK.WXApiImplV10(16069): handleIntent, cmd = 5
D/ViewContentFactory(16069): initViewContentFetcherClass
I/ContentCatcher(16069): ViewContentFetcher : ViewContentFetcher
D/ViewContentFactory(16069): createInterceptor took 0ms
E/WXPayEntryActivity(16069): 微信支付回调
E/WXPayEntryActivity(16069): errCode:-1
E/MicroMsg.SDK.WXApiImplV10(16069): handleIntent fail, ex = println needs a message
E/SyFlutterWechatPlugin>>(16069): -1

微信的文档里说：可能的原因：签名错误、未注册APPID、项目设置APPID不正确、注册的APPID与设置的不匹配、其他异常等。
现在签名验证通过，appId也注册正常。然后你的readme.md里说安卓不需要其他配置。。。
求大神看看可能是什么原因

**Comment by swellee** [comment]
原因是调试版的app跟release版的签名不一致

**Comment by Primer1889** [comment]
> 原因是调试版的app跟release版的签名不一致
前面的情况跟你的相同，并且我使用的签名也是正确的，最后还是没有拉起支付页面
